train: train/images
val: valid/images
test: test/images

nc: 15
names: ['0', '1', '10', '11', '12', '13', '14', '2', '3', '4', '5', '6', '7', '8', '9']

roboflow:
  workspace: anpr-data-set
  project: waste-aqmsf-dt2z6
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/anpr-data-set/waste-aqmsf-dt2z6/dataset/1